name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  publish-release:
    runs-on: ubuntu-latest
    if: github.repository == 'Lavmee/hilt-contributes-assisted-factory'
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
          check-latest: true
        
      - uses: gradle/gradle-build-action@v2

      - name: Publish Release
        run: ./gradlew clean publishAndReleaseToMavenCentral --no-build-cache --no-daemon --stacktrace --no-parallel

      - name: Extract release notes
        id: release_notes
        uses: ffurrer2/extract-release-notes@v2

      - name: Create release
        uses: softprops/action-gh-release@9d7c94cfd0a1f3ed45544c887983e9fa900f0564 # v2
        with:
          body: ${{ steps.release_notes.outputs.release_notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
